### ISSUE TITLE
Feature: Sales bell

### ISSUE THREAD

**Issue by surpher** [huwr/MacSniff#3]
# 🗣 Context

In order to feel more like in the open office environment, have a random bell ringing with loud clapping and woo sounds. This would simulate any of the sales made by the sales department sharing the area with software engineering team(s).

# 💬 Narrative

When running MacSniff
I want random bursts of bell ringing and loud clapping/cheering
So that I can get as annoyed just as I could be sitting in a real open office environment

# 📝 Notes

- ring-a-ding-ding bell, preferably playing for at least 6 seconds
- followed by loud cheering and applause

# 🏗 Design

# ✅ Acceptance Criteria

**GIVEN** I run MacSniff
**WHEN** I turn on the option to simulate environment sharing with sales department
**THEN** I randomly play loud bell ringing and applause/cheering/woos/yeahs 
**and** it plays for at least 38 seconds.

# 🚫 Out of Scope

**Comment by huwr** [comment]
Sales have been very low
